# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    # Installing python things
    # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
    - name: Install poetry
      run: pipx install poetry==1.5.1
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install python deps
      run: poetry install

    # Installing node things
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - name: Install node deps
      run: npm install

    - name: Updating tracks data
      run: poetry run python get_track_data.py
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

    # - name: Commit report
    #   run: |
    #     git config --global user.name 'Grady Lynn'
    #     git config --global user.email 'gradylynn@users.noreply.github.com'
    #     git commit -am "Automated report"
    #     git push

    - run: npm run build
    - run: ls -lah ./build
    - run: ls -lah ./build/static
    - run: pwd
    - run: git diff
    - run: date
