---
name: Build and Deploy App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    # Installing node things
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - name: Install node deps
      run: npm clean-install

    # build the app
    - run: npm run build

    # upload the artifact of static files for the app
    - name: Upload github pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: build/

  # From https://github.com/actions/deploy-pages#usage
  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to github Pages
        uses: actions/deploy-pages@v2
