---
name: Update Upcoming Track Schedule

on:
  schedule:
    - cron: '42 01 15 Jan,Apr,Jul,Oct *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}

    # Installing python things
    # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
    - name: Install poetry
      run: pipx install poetry==1.5.1
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install python deps
      run: poetry install

    - name: Updating tracks data
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 5
        retry_wait_seconds: 1800
        command: poetry run python get_track_data.py update_schedule
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

    # commit and push changes (if any exist)
    - name: Commit updated tracks data
      run: |
        git config --global user.name 'Grady Lynn'
        git config --global user.email 'gradylynn@users.noreply.github.com'
        git diff --quiet && git diff --staged --quiet || git commit -am "automated schedule update for $(date +'%B %Y')"
        git push
